version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - laravel-network
      - django-network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - rabbitmq
    ports:
      - "8010:8010"
    command: php artisan serve --host=0.0.0.0 --port=8010
    volumes:
      - ./my_events:/app
    networks:
      - laravel-network

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - rabbitmq
    ports:
      - "8011:8011"
    command: python manage.py runserver 0.0.0.0:8011
    volumes:
      - ./dockerTest:/code
    networks:
      - django-network

networks:
  laravel-network:
    driver: bridge
  django-network:
    driver: bridge
